### ISSUE TITLE
передача ИНН в сервис atol.online при формировании чека

### ISSUE THREAD

**Issue by simformer** [Platron/atol.online#10]
АТОЛ требует чтобы ИНН, в запросе на создание чека, приходил с типом 'строка' (в кавычках). Ваш код допускает ввод ИНН в виде числа, которое затем сериализуется без кавычек и приводит к ошибке в ответе от сервиса atol.online.

Следует изменить реализацию метода Platron\Atol\services\CreateDocumentRequest::addInn($inn)
на 
/**
     * Установить inn
     * @param type $inn
     * @return CreateDocumentRequest
     */
    public function addInn($inn){
        $this->inn = (string)$inn;
        return $this;
    }

чтобы избежать этой проблемы.

**Comment by lashnag** [comment]
Добрый день! Поменяю. В следующий раз можете сразу отправить pull request. Я его проверю и сделаю merge
