### ISSUE TITLE
Поддержка ФФД 1.05

### ISSUE THREAD

**Issue by sergomor** [Platron/atol.online#11]
С 01.01.2019 года все онлайн-кассы должны передавать чеки по версии формата фискальных документов (ФФД) 1.05. ФФД – это протокол или иначе набор правил, по которому касса передает чеки в ФНС через оператора фискальных данных.

Реализован ли протокол в вашем пакете? Если нет, планируете ли вы его поддерживать в ближайшее время (в течении 5 -10 дней)?

**Comment by lashnag** [comment]
Добрый день. Это пакет с поддержкой ФФД 1.05

**Comment by sergomor** [comment]
Ваш код работает с API atol v3 а это реализация ФФД 1.0

**Comment by lashnag** [comment]
Прошу прощения. Предполагал, что вы про другой репозиторий. Есть репозиторий новый для поддержки ФФД 1.05 https://github.com/Platron/atol-sdk-api-v4

К сожалению, он не совместим со старым по причине того, что Atol сломал обратную совместимость в своем API

**Comment by sergomor** [comment]
Понятно. Если вы поддерживаете код для https://github.com/Platron/atol-sdk-api-v4, вам следует иправить readme 
вместо:
composer require payprocessing/atol-online
надо:
composer require payprocessing/payprocessing/atol-sdk-api-v4

а то composer устанавливает старую (v3) версию

**Comment by lashnag** [comment]
Спасибо, исправим!
