### ISSUE TITLE
Добавление метода CreateDocumentRequest->addCallbackUrl

### ISSUE THREAD

**Issue by mavDev** [Platron/atol.online#2]
Добрый день, не затруднит ли Вас добавить данный метод?

/** @var string */
    protected $callbackUrl;

/**
     * Задать URL на который будет отправлен ответ после обработки документа (фискализации в ККТ)
     * @param string $callbackUrl
     * @return CreateDocumentRequest
     */
    public function addCallbackUrl($callbackUrl){
        $this->callbackUrl = $callbackUrl;
        return $this;
    }

и изменить CreateDocumentRequest->getParameters(){
...
 'callback_url' => $this->callbackUrl,
...
}

**Comment by lashnag** [comment]
Сделал push. На будущее жду от Вас pull_request

**Comment by mavDev** [comment]
Большое спасибо! Я не очень умелый пользователь GitHub, буду иметь в виду и постараюсь в другой раз разобраться с pull_request.
