### ISSUE TITLE
Не хватает лицензии

### ISSUE THREAD

**Issue by kirmorozov** [Platron/atol.online#3]
Добропорядочные коллеги,
Под какой лицензией распространяется код?

**Comment by lashnag** [comment]
Добрый день! При использовании открытых репозиториев на GitHub человек соглашается с тем, что весь выложенный код может использоваться в любых целях - как коммерческих, так и не коммерческих.
Какой именно вид лицензии можно для этого использовать не знаю. Код был написал на "общественных началах"

**Comment by kirmorozov** [comment]
Доброго,
Юридически, прав которые можно дать в лицензии много.
Если код остается открытый то  MIT, Apache, BSD, GPL подходят.
GPL обязует делиться модификациями.
Apache/MIT обязует уведомлять если код является частью системы, сохранять ссылку на автора.

Я просто хочу ссылаться на этот репозиторий для реализации модуля Magento.

**Comment by lashnag** [comment]
Добавил MIT. Спасибо!
