### ISSUE TITLE
Ошибка PHP

### ISSUE THREAD

**Issue by kulaginds** [Platron/atol.online#5]
Fatal error: Can't use function return value in write context in /home/*****/modules/gateways/qiwi/vendor/payprocessing/atol-online/src/clients/PostClient.php on line 62

PHP Version 5.3.29

Исправил у себя локально вынесением json_decode($response) в переменную, её же подставляю в empty и всё проходит без ошибок.

**Comment by lashnag** [comment]
Вероятно Atol вообще ничего не ответил. Добавил проверку на пустой ответ

**Comment by kulaginds** [comment]
Обновил. Та же ошибка.
Fatal error: Can't use function return value in write context in /home/*****/modules/gateways/qiwi/vendor/payprocessing/atol-online/src/clients/PostClient.php on line 60

Тут скорее проблема в PHP, чем в Атол.

**Comment by lashnag** [comment]
Сделайте var_dump и пришлите что у вас хранится в переменной и версию php

**Comment by kulaginds** [comment]
PHP Version 5.3.29

В файле vendor/payprocessing/atol-online/src/clients/PostClient.php на строке 60 после curl_errno добавил var_dump.
Результат: string(65) "{"code":1,"text":null,"token":"02d7\*\*37fc3\*\*a4697563\*\*12b48c\*\*5"}"

Я решил проблему, когда вынес результат json_decode в переменную $response_decoded:
$response_decoded = json_decode($response);

if(empty($response_decoded)){
    throw new SdkException('Atol error. Empty responce or not json response');
}

return $response_decoded;

**Comment by lashnag** [comment]
Решать баг нужно понимая, что делаешь. Причина в php 5.3. Он не позволяет использовать json_decode без присвоения. Я сделаю коммит, раз написано, что версия php 5.3 поддерживается. В следующий раз можете прислать pull_request - я его проверю и сделаю merge
