### ISSUE TITLE
Версия 4

### ISSUE THREAD

**Issue by Tamidin** [Platron/atol.online#9]
Добрый день.
На сегодняшний день Атол выпустили 4 версию протокола, поддержку 3 планируют прекратить в июне 2018 года.
Готовите ли вы обновление проекта? Если да, то в какие сроки?

**Comment by lashnag** [comment]
Добрый день! У Вас есть информация о том, что обновилось в новой версии?

**Comment by Tamidin** [comment]
Есть Pdf с информацией о версии: https://yadi.sk/i/XNTmygz73S33Dc 
Взят с официального телеграмм-канала: https://t.me/atolonline

**Comment by lashnag** [comment]
В документации написано, что поддержка v3 осуществляется до 1 января 2019 года. Пока обновление не предполагалось. Но если у Вас есть возможность обновить SDK под версию v4 - можете сделать pull request. В базовом классе добавить метод получения заголовков в POST запросе + в базе возвращается Content-type: application/json; charset=utf-8.
Так же добавить в ответе error_id и пройтись по всем полям прошлой версии - сверить - не изменились ли они.
